env:
  browser: true
  es2021: true
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - css
  - jest
extends:
  - google
  - plugin:react/recommended
  - plugin:css/all
  - next/core-web-vitals
  - eslint:all
  - eslint-plugin-jest/all
rules: 
  require-jsdoc: off
  func-style: off
  no-ternary: off