env:
  browser: true
  es2021: true
extends:
  - google
  - plugin:react/recommended
  - next/core-web-vitals
  - eslint:recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {}